### ISSUE TITLE
Add split_element to convert one element into a few other elements

### ISSUE THREAD

**Issue by iliiliiliili** [LukasHedegaard/datasetops#26]
Currently, to create new elements from another we can use `dataset.transform(lambda x: (x[0], make_P(x[1]), make_R(x[1]), x[2]))`. This approach breaks dataset names, so we have to call `.named(...)` after it.
Implementing `split_element` method that takes name of the (element, function, that returns `List` with created elements, `List[str]` of names of new elements) allows us to process the data without the need to touch other data, so less chances for user to make an error.

**Comment by LukasHedegaard** [comment]
I'm on the verge on this... This functionality may be too specific, and I fear it may just produce unnecessary clutter. 

What is your take, @clegaard ?
We recently had a discussion that we might want to split elements across multiple items (not within an item, like here). If we can come up with an intuitive naming scheme and API for the two functionalities, it might be worth pursuing.

**Comment by clegaard** [comment]
I have implemented this as a an operation *subsample*, which uses a user-defined function to split each sample.

**Comment by LukasHedegaard** [comment]
I don't think the thing you have @clegaard implemented is what @iliiliiliili was looking for. You split a sample into multiple samples. @iliiliiliili asked for a method which splits an element in a single sample into multiple elements, e.g. `(a,b) -> (a1, a2, b)`.

**Comment by clegaard** [comment]
I guess a transform is a right way to go then, only issue is the naming. 
I am also on the too specific side on this one, since a transform + named can achieve the same

**Comment by LukasHedegaard** [comment]
Closing for now
